apiVersion: v1
kind: Service
metadata:
  name: postgres_service
  labels:
    name: postgres_service
    app: demo_voting_app
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    name: postgres_pod
    app: demo_voting_app
