apiVersion: v1
kind: Pod
metadata:
  name: postgres_pod
  labels:
    name: postgres_pod
    app: demo_voting_app
spec:
  containers:
  - name: postgres
    image: postgres
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_PASSWORD
      value: "postgres"
