apiVersion: v1
kind: Service
metadata:
  name: redis_service
  labels:
    name: redis_service
    app: demo_voting_app
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis_pod
    app: demo_voting_app
