apiVersion: v1
kind: Service
metadata:
  name: result_app_service
  labels:
    name: result_app_service
    app: demo_voting_app
spec:
  type: NodePort
  ports:
  - port: 80
    targetport: 80
    nodeport: 30005
  selector:
    name: result_app_pod
    app: demo_voting_app
