apiVersion: v1
kind: Service
metadata:
  name: voting_app_service
  labels:
    name: voting_app_service
    app: demo_voting_app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodeport: 30004
  selector:
    name: voting_app_pod
    app: demo_voting_app
